### ISSUE TITLE
codecs CELT 

### ISSUE THREAD

**Issue by nvjacobo** [digitalautonomy/wahay#1]
Hi, 

It's my first time here.

My setup  
- Debian 10 
- Wahay-debian-10-2020-03-10-85a2c28

Dependency message:

"No se pudieron encontrar codecs CELT adecuados para los otros clientes. No podrá hablar a todos los usuarios"

Thanks, Jacobo

**Comment by Cris2760** [comment]
Thank you very much for your feedback @nvjacobo 
We going to verify it, once we correct it we will let you know
Thanks.

**Comment by rafaelbonifaz** [comment]
Hey @nvjacobo, sorry for the delay.

Can you please test with this binary:
https://staging.wahay.org/downloads/wahay-debian-10-latest.tar.bz2

I think I fixed the error.

**Comment by nvjacobo** [comment]
Thanks @rafaelbonifaz 

I tested wahay-debian-10-latest.tar.bz2. It works correctly without celt errors!

Seguimos, Jacobo

**Comment by rafaelbonifaz** [comment]
Thanks, great
