### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by trymeouteh** [digitalautonomy/wahay#10]
Please make an Android app once the desktop apps are done. And please release the Android app on F-Droid so degoogle Android users can download the app.

**Comment by olabiniV2** [comment]
Hi,

Thanks for the suggestion. An Android app is not on our current roadmap for Wahay - it would not really be possible to do it based on the current ecosystem. You can however use Mumbla together with Orbot to connect to Wahay meetings from Android.

**Comment by trymeouteh** [comment]
I can use Mumble, Mumla or Plumble to connect to a Wahay meeting? Is a Wahay meeting essentially a Murmur server that can be self hosted on someones computer and runs over Tor to protect the hosts IP?

**Comment by rafaelbonifaz** [comment]
> I can use Mumble, Mumla or Plumble to connect to a Wahay meeting?

Yes, Plumble or Mumbla with Orbot. However avoid using Plumble that is no longer being maintain, use Mumla that is the fork.
To connect from Linux you can do something link
```
torsocks mumble://longOnionUrl.onion
```

> Is a Wahay meeting essentially a Murmur server that can be self hosted on someones computer and runs over Tor to protect the hosts IP?

You are close. We are not using Murmur, instead with are using Grumble that is a Go implementation of the Mumble server. We use Tor Onion services to expose the Mumble server to the Tor network. Onion services have two nice properties:

1. Autonomy: you don't need a public IP, all you need is a normal Internet connection that allows you to connect to the Tor network for running a TCP server (It could be Murmur)
2. Security: all communications are always encrypted between clients and server, and the IPs remain anonymous. That is true for both clients and server.

You could connect to Wahay from a torify Mumble, however Wahay is meant for ephemeral meetings and the URL is going to change every-time. I understand you are interesting in Wahay for video games, in that case it might be nice to have a long living onion url. So you could try running your own Mumble server and publish it as an onion url.

- I wrote this [article](https://medium.com/@facceso.ca/comunicaciones-secretas-y-aut%C3%B3nomas-de-voz-ip-con-mumble-3b3d3bad06c5) a couple of years ago, it is Spanish, but you can take a look to the commands. If you have little knowledge of Linux system administration, it would be straightforward.
- You might also want to take a look to the scripts created in @digitalautonomy for[ running Mumble in Tails](https://github.com/digitalautonomy/mumble_with_tails). There is also a [blogpost](https://autonomia.digital/2019/10/09/tails-mumble.html) related that you might want to read. 
- The [Whonix wiki](https://www.whonix.org/wiki/VoIP#Mumble) has some info related to this too. 

Good luck!

Rafael

**Comment by trymeouteh** [comment]
Here is my predicament

I want to have a privacy respecting gaming voice chat app that is open source, uses encryption to ensure no one can eavesdrops on the chat and be able to either host a server or P2P chat. I also want this to be available on Windows, Linux, Android and iOS.

Discord is popular but has horrible privacy. Teamspeak is proprietary, Mumble is great and checks all the boxes except hosting a server is not user friendly and if you host a server on your computer you will expose your IP address and be vulnerable to a DDoS attack. And there is no way to use a VPN when hosting a mumble server or to easily run a Mumble server over Tor. I know you can pay for hosting and have a Mumble serve but that costs money and it is too much money for something I will not use all the time.
