### ISSUE TITLE
Listening on 127.0.0.1 might cause problems when Wahay and Tor on different machines

### ISSUE THREAD

**Issue by JeremyRand** [digitalautonomy/wahay#12]
Based on https://github.com/digitalautonomy/wahay/blob/7c21ce4e8e61ca65b3dddb472e08cf39f18c14b2/hosting/service.go#L23 , it looks like Wahay is listening for incoming connections via the `127.0.0.1` network interface?  If that's accurate, it seems like that would cause problems for users who are running Wahay and Tor on different machines (e.g. Whonix).  Is there some workaround for this already in the code that I didn't find?  If there's no workaround, may I request adding support for listening on other network interfaces, so that Whonix-style use cases will work?

**Comment by rafaelbonifaz** [comment]
Hello @JeremyRand it makes sense to add support for different IP for the Tor connection, specially for projects like Whonix. We are going to work on this issue later as for now CAD's team is working on [Multi Chat Support for CoyIM](https://github.com/coyim/coyim/issues?q=is%3Aissue+is%3Aopen+label%3AMUC).

Thanks a lot for trying Wahay and your feedback.

Rafael

**Comment by JeremyRand** [comment]
> We are going to work on this issue later as for now CAD's team is working on [Multi Chat Support for CoyIM](https://github.com/coyim/coyim/issues?q=is%3Aissue+is%3Aopen+label%3AMUC).

Not promising that I'll have time for this, but would things move along faster if I contributed a PR for this?

**Comment by rafaelbonifaz** [comment]
Yes, sure! This is an open source project, contribution from community is always appreciated.

**Comment by HulaHoop0** [comment]
@rafaelbonifaz @wybiral Hi what's the status on this ticket?  with https://github.com/wybiral/torgo/pull/3 and https://github.com/wybiral/torgo/pull/4 merged, the linked pull request should do it.
