### ISSUE TITLE
User hosting a meeting doesn't need to connect via onion

### ISSUE THREAD

**Issue by JeremyRand** [digitalautonomy/wahay#13]
As far as I can tell, all users who are connected to a meeting access it via the onion service.  If that's accurate, it seems wasteful to make the user who's hosting the meeting do so, since they don't need to stay anonymous from themselves.  Making the user who's hosting a meeting connect via localhost instead of the onion service would cut the latency in half for 2-party calls, and would improve the latency for the portions of conference calls where the host is a participant as well.  Is there any security rationale for not doing so that I'm overlooking?

**Comment by rafaelbonifaz** [comment]
You are raising a valid concern, and we had discuss this internally. Handing special cases is not the best to keep the code simple and secure. Also this could be a problem with systems like Tails that does all its networking with Tor.

I know this is not what you want, but you can try the following:
- Start  a Wahay meeting without joining.
- Find the port that mumble is listeninng (Wahay uses random ports):
```
netstat  -ptan | grep wahay
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:41847         0.0.0.0:*               LISTEN      5875/wahay          
tcp        0      0 127.0.0.1:37887         0.0.0.0:*               LISTEN      5875/wahay          
tcp        0      0 127.0.0.1:36480         127.0.0.1:9051          ESTABLISHED 5875/wahay
```
In this example `127.0.0.1:41847`
- Now you can use this information to join from a mumble client. From command line you can do something like:
```
mumble mumble://user@127.0.0.1:41847
```

**Comment by JeremyRand** [comment]
> Also this could be a problem with systems like Tails that does all its networking with Tor.

Hmm, does Tails prevent applications from opening connections to `127.0.0.1`?  I don't use Tails regularly, so I'm not very familiar with it, but I would have assumed it would only force external network traffic over Tor.

> Handing special cases is not the best to keep the code simple and secure.

FWIW my intuition is that there may be a mild security advantage to keeping that traffic off of the network and not needing to generate an extra Tor circuit for this.  E.g. sending what's basically the same traffic over 2 Tor circuits instead of 1 might make traffic analysis easier since there's a bigger chance you'll wind up with compromised relays on one of your circuits.

It also might be argued that sending the same traffic over 2 Tor circuits instead of 1 puts unnecessary load on the Tor network, so using `127.0.0.1` for this might be being a better Tor citizen.

**Comment by rafaelbonifaz** [comment]
We might show the local information 127.0.0.1:port so it would be easier to connect from a non torrify Mumble. Thanks a lot for your feedback and for using Wahay.
