### ISSUE TITLE
[Question] Update Install Documentation with AUR Package.

### ISSUE THREAD

**Issue by LaurentFough** [digitalautonomy/wahay#18]
I've created an Arch Linux package in the AUR for (easy)wahay install.

Package here: [aur.archlinux.org/ packages/ wahay-bin/](https://aur.archlinux.org/packages/wahay-bin/)

Are you accepting PRs to the README#Install, or can you update the website with a link to the install?

**Comment by olabiniV2** [comment]
A PR would be great, thank you! Once we have that, we can add it to the website as well.

**Comment by rafaelbonifaz** [comment]
I don't use Arch, but I have asked arch people to install and it seems to work. The only issue that they report to me is that torsocks should be a dependency: https://aur.archlinux.org/packages/wahay-bin/#comment-794371

What should be the installation instructions?

**Comment by da-edra** [comment]
Hi @rafaelbonifaz , the installation instructions could vary greatly from user to user as there are many AUR helpers that a user could be using however, I've seen that most users are using `yay` nowadays so the installation instructions could be something like:

`yay -S wahay-bin`

And thanks a lot @LaurentFough for creating the PKGBUILD!

**Comment by rafaelbonifaz** [comment]
I updated the instructions for Arch. @LaurentFough, @da-edra is that good enough? Should I add something? I understund that this should work also for Manjaro and other Arch base distributions.

**Comment by rafaelbonifaz** [comment]
I asked several Arch users to test the installation instructions, it seems to be all right. Thanks a lot!

**Comment by LaurentFough** [comment]
bump.

Updated the package on AUR to better reflect the torsocks dependency as well.
