### ISSUE TITLE
Lyra codec for video conferences over low bandwidth connections

### ISSUE THREAD

**Issue by HulaHoop0** [digitalautonomy/wahay#19]
Hi. Google released Lyra, a video codec that is supposed to work over very low bandwidth connections like 56K dial-up connections. I wonder if it can be integrated to accomplish low latency video conferencing over Tor. Would be very cool :)

https://www.phoronix.com/scan.php?page=news_item&px=Google-Lyra

**Comment by olabiniV2** [comment]
Thank you for the suggestion, but Wahay is not really meant to implement these kinds of features. We rely heavily on Mumble for all the audio-codec stuff - Wahay is basically glue between Tor onion services and Mumble. 

I do think it's an interesting idea to investigate Lyra in conjunction with Tor. Sadly, I don't think Wahay is the right project to do that research in, though.
