### ISSUE TITLE
Create an appimage and relax

### ISSUE THREAD

**Issue by TNTBOMBOM** [digitalautonomy/wahay#21]
Looking at https://wahay.org/download.html it says alot of headache to support multiple Linux distros, Well the solution is simple by just having 1 image for all of the distros through https://appimage.org/ and some advantages of having that are:

- No need multiple builds for multiple distros
- Support inline-upgrade (No need to download the new releases by checking the main website over and over) (check https://docs.appimage.org/packaging-guide/optional/updates.html , https://github.com/AppImage/AppImageUpdate )
- Run within user privileges/read-only (No installation required which is a security benefit since no root needed)
- Support sandboxing (Probably not straight forward without issues e.g [#550](https://github.com/AppImage/AppImageKit/issues/550) , [#839](https://github.com/AppImage/AppImageKit/issues/839) , [#452](https://github.com/AppImage/AppImageKit/issues/452))

**Comment by olabiniV2** [comment]
Honestly, AppImage has not been very impressive to us. It has lots of problems, and for now we will focus on supporting the operating systems directly.
