### ISSUE TITLE
Hardenize The Website

### ISSUE THREAD

**Issue by TNTBOMBOM** [digitalautonomy/wahay#23]
Checking the website security configurations through: 

- https://www.hardenize.com/report/wahay.org/1614942638
- https://www.ssllabs.com/ssltest/analyze.html?d=wahay.org
- https://securityheaders.com/?q=https%3A%2F%2Fwahay.org%2F&followRedirects=on (F)

Website TLS/DNS/Headers... need to have alot of improvements hope these reports show where/what work need to be done.

**Comment by rafaelbonifaz** [comment]
Thanks a lot @TNTBOMBOM, with @peterpalau we had hardenized the website. The only thing that is missing at the time is HSTS preload, we are waiting for our submission to be approved in [hstspreload.org](https://hstspreload.org/?domain=wahay.org).

**Comment by TNTBOMBOM** [comment]
I hope as well to see if you can have DNSSEC , CAA (both recommended as 
mandatory) And might be good idea as well for future security to have 
ESNI effective (from user side) which require to have TLS 1.3 enabled on 
the server side.

You welcome anytime :)

Rafael Bonifaz:
> Thanks a lot @TNTBOMBOM, with @peterpalau we had hardenized the website. The only thing that is missing at the time is HSTS preload, we are waiting for our submission to be approved in [hstspreload.org](https://hstspreload.org/?domain=wahay.org).
>
