### ISSUE TITLE
Bump vendored torgo

### ISSUE THREAD

**Issue by JeremyRand** [digitalautonomy/wahay#25]
The vendored `torgo` dependency was last updated in this repo in 2019.  Upstream has since merged some improvements (specifically https://github.com/wybiral/torgo/pull/3 and https://github.com/wybiral/torgo/pull/4) that would be helpful for running Wahay under Whonix.  Any chance the vendored `torgo` could be bumped to latest from upstream?

**Comment by olabiniV2** [comment]
Thanks, Jeremy. Good suggestion - this has been done now.
