### ISSUE TITLE
chat / persistent sessions

### ISSUE THREAD

**Issue by adrelanos** [digitalautonomy/wahay#28]
> The conference URLs are ephemeral and exist only for the time of the meeting. This makes it harder for someone to get into a meeting without being invited.

Certainly a valid viewpoint.

However, constantly re-creating sessions is tedious. Then one also has to always re-share the secret join link over a pre-secure channel. And due to usability issues, many users are short of pre-secure channels.

For me, it's much more convenient to once set up a messenger and then have something like a contract list where people can be re-contacted later.

There's also currently as far as I know no onion to onion messenger. (TorChat was but was abandoned, never got onion v3 support.)

Could you please consider extending wahay to become a chat (re-using mumble chat feature)?

**Comment by rafaelbonifaz** [comment]
Persistent meeting IDs is something we want to do in the future.  

What Wahay does is integrate Mumble with Tor. You can use the chat in Mumble, but that is not purpose of Wahay.  Briar, Ricochet and Cwtch sounds more like what you are looking for in respect to chat.

**Comment by olabiniV2** [comment]
As Rafael mentioned, this is quite far outside the use case of Wahay. There are chat applications you can use for this purpose, and you can also use the Mumble chat for this purpose.
