### ISSUE TITLE
Group chat in Wahay meetings

### ISSUE THREAD

**Issue by rafaelbonifaz** [digitalautonomy/wahay#3]
Mumble normally has a group chat that allows people to write during a meeting. This is useful when some has issues with audio, or to ask questions without interrupting the speaker. However this chat function is not working in Wahay, you can only do one on one chats.

**Comment by olabiniV2** [comment]
This has been fixed in the latest commit, by fixing missing functionality in Grumble, where it never sent permission information to a client that requested it.
