### ISSUE TITLE
Cannot generate translations when working on fork repository

### ISSUE THREAD

**Issue by IvanJijon** [digitalautonomy/wahay#5]
### Expected Behavior
When running `$ make gen-ui-locale` on root folder the execution should succeed generating file `/gui/catalog/catalog.go` using lang files in `/gui/locales` (ar, en, es, ...).

### Actual Behavior

The command `$ make gen-ui-locale` exits with errors :

```
cd gui && make generate-locale
make[1]: Entering directory '/home/[username]/go/src/github.com/[username]/wahay/gui'
# This beautiful code is necessary because gotext
# will barf if the golang.org/x/text/message package
# exists in the vendor directory when running...
# The world of programming is beautiful
rm -rf ../vendor/golang.org/x/text
go generate -x i18n.go
gotext -srclang=en update -out=catalog/catalog.go -lang=en,es,sv,ar,fr
/home/[username]/go/src/github.com/[username]/wahay/gui/i18n.go:23:28: cannot use tag (variable of type language.Tag) as language.Tag value in argument to message.NewPrinter
gotext: extract failed: : : couldn't load packages due to errors: github.com/[username]/wahay/gui
i18n.go:3: running "gotext": exit status 1
Makefile:2: recipe for target 'generate-locale' failed
make[1]: *** [generate-locale] Error 1
make[1]: Leaving directory '/home/[username]/go/src/github.com/[username]/wahay/gui'
Makefile:26: recipe for target 'gen-ui-locale' failed
make: *** [gen-ui-locale] Error 2
```
### Steps to Reproduce the Problem

  1. Fork https://github.com/digitalautonomy/wahay on GitHub
  1. `go get` your fork (ex : https://github.com/[username]/wahay)
  1. `cd` to your fork location (ex: ~/go/src/github.com/[username]/wahay)
  1. Verify that `make build` runs without problems from root folder
  1. Execute `make gen-ui-locale`

### Specifications
Version: current
OS: Ubuntu 18.04 
IDE: Visual Studio Code 1.45.1

### Additional information
- The command runs without problems when working on main repository
- When on main repository folder, my IDE (vscode) shows no warning ; but when working on fork repository folder I get this highlight in file `i18n.go` on line 23:
`i18n = message.NewPrinter(tag, message.Catalog(message.DefaultCatalog))`

_cannot use tag (type "github.com/digitalautonomy/wahay/vendor/golang.org/x/text/language".Tag) as type "github.com/[username]/wahay/vendor/golang.org/x/text/language".Tag in argument to message.NewPrinter_

**Comment by MauroVelasco** [comment]
New translations in Wahay can be done in the following way:

Fork wahay  under a directory with the structure:

$GOPATH/src/github.com/digitalautonomy/wahay

Another important thing is add $GOPATH/bin to $PATH

In this point the following commands must run without issues inside $GOPATH/src/github.com/digitalautonomy/wahay:

$ make deps
$ make default

To add a new language translation add the required folder under locales for example fr:
src/github.com/digitalautonomy/wahay/gui/locales/fr

After that copy one of the messages.gotext.json files of en or es folders to use as a reference. In this file also is required set the code of language to be used, for example:  "language": "fr" and add all the translations in translation tag:
{
    "id": "Welcome",
    "message": "Welcome",
    "translation": "Bienvenue"
}

After that modify i18.go (//go:generate gotext -srclang=en update -out=catalog/catalog.go -lang=en,es,sv,ar) to add the new language to be translated:
//go:generate gotext -srclang=en update -out=catalog/catalog.go -lang=en,es,sv,ar,fr

Now its possible execute: **make gen-ui-locale** under src/github.com/digitalautonomy/wahay, finally 
execute **make default**

To check the new language its possible use: export LANG="fr_FR.utf8"

![fr](https://user-images.githubusercontent.com/2516223/84445140-f8aca000-ac08-11ea-8fd3-a6da04451172.png)

**Comment by MauroVelasco** [comment]
> ### Expected Behavior
> 
> When running `$ make gen-ui-locale` on root folder the execution should succeed generating file `/gui/catalog/catalog.go` using lang files in `/gui/locales` (ar, en, es, ...).
> ### Actual Behavior
> 
> The command `$ make gen-ui-locale` exits with errors :
> 
> ```
> cd gui && make generate-locale
> make[1]: Entering directory '/home/[username]/go/src/github.com/[username]/wahay/gui'
> # This beautiful code is necessary because gotext
> # will barf if the golang.org/x/text/message package
> # exists in the vendor directory when running...
> # The world of programming is beautiful
> rm -rf ../vendor/golang.org/x/text
> go generate -x i18n.go
> gotext -srclang=en update -out=catalog/catalog.go -lang=en,es,sv,ar,fr
> /home/[username]/go/src/github.com/[username]/wahay/gui/i18n.go:23:28: cannot use tag (variable of type language.Tag) as language.Tag value in argument to message.NewPrinter
> gotext: extract failed: : : couldn't load packages due to errors: github.com/[username]/wahay/gui
> i18n.go:3: running "gotext": exit status 1
> Makefile:2: recipe for target 'generate-locale' failed
> make[1]: *** [generate-locale] Error 1
> make[1]: Leaving directory '/home/[username]/go/src/github.com/[username]/wahay/gui'
> Makefile:26: recipe for target 'gen-ui-locale' failed
> make: *** [gen-ui-locale] Error 2
> ```
> 
> ### Steps to Reproduce the Problem
> 
>     1. Fork https://github.com/digitalautonomy/wahay on GitHub
> 
>     2. `go get` your fork (ex : [https://github.com/[username]/wahay](https://github.com/%5Busername%5D/wahay))
> 
>     3. `cd` to your fork location (ex: ~/go/src/github.com/[username]/wahay)
> 
>     4. Verify that `make build` runs without problems from root folder
> 
>     5. Execute `make gen-ui-locale`
> 
> 
> ### Specifications
> 
> Version: current
> OS: Ubuntu 18.04
> IDE: Visual Studio Code 1.45.1
> ### Additional information
> 
>     * The command runs without problems when working on main repository
> 
>     * When on main repository folder, my IDE (vscode) shows no warning ; but when working on fork repository folder I get this highlight in file `i18n.go` on line 23:
>       `i18n = message.NewPrinter(tag, message.Catalog(message.DefaultCatalog))`
> 
> 
> _cannot use tag (type "github.com/digitalautonomy/wahay/vendor/golang.org/x/text/language".Tag) as type "github.com/[username]/wahay/vendor/golang.org/x/text/language".Tag in argument to message.NewPrinter_

Please check if GOPATH env variable has been created and wahay can be found under:
$GOPATH/src/github.com/digitalautonomy/wahay

For a more detailed list of steps to configure wahay please check https://github.com/digitalautonomy/wahay/issues/5#issuecomment-642963885

**Comment by IvanJijon** [comment]
Solved !

Following the solution @MauroVelasco proposed I took a little shortcut :

1. Forked your repo on GitHub
1. Cloned your repo via `go get`
1. Changed origin URL to point to my fork repo
