### ISSUE TITLE
Feature Request: Game Overlay

### ISSUE THREAD

**Issue by trymeouteh** [digitalautonomy/wahay#9]
Please add a feature to have a Wahay overlay in games. The Mumble overlay is a great overlay that works. This will make Wahay a good gaming voice chat since Wahay does not require a server like Mumble and Mumble servers cost money and Discord has poor privacy.

Gaming Overlay in games
Overlay hotkey (A setting to choose the overlay hotkey)
Overlay shows who is talking

**Comment by olabiniV2** [comment]
Hi, thanks for the suggestion.

The purpose of Wahay is primarily to provide more secure communications to people at risk. Integrating Wahay with games doesn't really match those goals, and is not something we are planning on doing.
